### ISSUE TITLE
Unclear on how to add Test2Code plugin

### ISSUE THREAD

**Issue by BalasubramanyamEvani** [Drill4J/test2code-plugin#100]
Hi, I've been following the documentation as stated https://drill4j.github.io/how-to-start/, I'm using the sample Sprint boot application PetClinic as example agent, Till step 3 i had no problem.. I see the application is running on port 8080 and on 8091 the admin panel is there.. now in **Step 4** do i need to add the browser extension in order to add the Test2Code plugin or is it fine if I don't ?

Can you help me understand this ? Thank you

**Comment by viktorbll** [comment]
Hi @BalasubramanyamEvani. Test2Code plugin is added during registration of an agent. The browser extension is needed for manual testing, i.e. starting and stopping of sessions.
